// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"sync"

	"github.com/tobyrushton/fantasy-nba/pkg/db/models"
)

type FakeRepo struct {
	CreateLeagueStub        func(context.Context, string, int64) (*models.League, error)
	createLeagueMutex       sync.RWMutex
	createLeagueArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 int64
	}
	createLeagueReturns struct {
		result1 *models.League
		result2 error
	}
	createLeagueReturnsOnCall map[int]struct {
		result1 *models.League
		result2 error
	}
	CreateUserStub        func(context.Context, string, string) (*models.User, error)
	createUserMutex       sync.RWMutex
	createUserArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	createUserReturns struct {
		result1 *models.User
		result2 error
	}
	createUserReturnsOnCall map[int]struct {
		result1 *models.User
		result2 error
	}
	GetLeaguesStub        func(context.Context) ([]*models.League, error)
	getLeaguesMutex       sync.RWMutex
	getLeaguesArgsForCall []struct {
		arg1 context.Context
	}
	getLeaguesReturns struct {
		result1 []*models.League
		result2 error
	}
	getLeaguesReturnsOnCall map[int]struct {
		result1 []*models.League
		result2 error
	}
	GetUserByUsernameStub        func(context.Context, string) (*models.User, error)
	getUserByUsernameMutex       sync.RWMutex
	getUserByUsernameArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getUserByUsernameReturns struct {
		result1 *models.User
		result2 error
	}
	getUserByUsernameReturnsOnCall map[int]struct {
		result1 *models.User
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRepo) CreateLeague(arg1 context.Context, arg2 string, arg3 int64) (*models.League, error) {
	fake.createLeagueMutex.Lock()
	ret, specificReturn := fake.createLeagueReturnsOnCall[len(fake.createLeagueArgsForCall)]
	fake.createLeagueArgsForCall = append(fake.createLeagueArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 int64
	}{arg1, arg2, arg3})
	stub := fake.CreateLeagueStub
	fakeReturns := fake.createLeagueReturns
	fake.recordInvocation("CreateLeague", []interface{}{arg1, arg2, arg3})
	fake.createLeagueMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRepo) CreateLeagueCallCount() int {
	fake.createLeagueMutex.RLock()
	defer fake.createLeagueMutex.RUnlock()
	return len(fake.createLeagueArgsForCall)
}

func (fake *FakeRepo) CreateLeagueCalls(stub func(context.Context, string, int64) (*models.League, error)) {
	fake.createLeagueMutex.Lock()
	defer fake.createLeagueMutex.Unlock()
	fake.CreateLeagueStub = stub
}

func (fake *FakeRepo) CreateLeagueArgsForCall(i int) (context.Context, string, int64) {
	fake.createLeagueMutex.RLock()
	defer fake.createLeagueMutex.RUnlock()
	argsForCall := fake.createLeagueArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeRepo) CreateLeagueReturns(result1 *models.League, result2 error) {
	fake.createLeagueMutex.Lock()
	defer fake.createLeagueMutex.Unlock()
	fake.CreateLeagueStub = nil
	fake.createLeagueReturns = struct {
		result1 *models.League
		result2 error
	}{result1, result2}
}

func (fake *FakeRepo) CreateLeagueReturnsOnCall(i int, result1 *models.League, result2 error) {
	fake.createLeagueMutex.Lock()
	defer fake.createLeagueMutex.Unlock()
	fake.CreateLeagueStub = nil
	if fake.createLeagueReturnsOnCall == nil {
		fake.createLeagueReturnsOnCall = make(map[int]struct {
			result1 *models.League
			result2 error
		})
	}
	fake.createLeagueReturnsOnCall[i] = struct {
		result1 *models.League
		result2 error
	}{result1, result2}
}

func (fake *FakeRepo) CreateUser(arg1 context.Context, arg2 string, arg3 string) (*models.User, error) {
	fake.createUserMutex.Lock()
	ret, specificReturn := fake.createUserReturnsOnCall[len(fake.createUserArgsForCall)]
	fake.createUserArgsForCall = append(fake.createUserArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.CreateUserStub
	fakeReturns := fake.createUserReturns
	fake.recordInvocation("CreateUser", []interface{}{arg1, arg2, arg3})
	fake.createUserMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRepo) CreateUserCallCount() int {
	fake.createUserMutex.RLock()
	defer fake.createUserMutex.RUnlock()
	return len(fake.createUserArgsForCall)
}

func (fake *FakeRepo) CreateUserCalls(stub func(context.Context, string, string) (*models.User, error)) {
	fake.createUserMutex.Lock()
	defer fake.createUserMutex.Unlock()
	fake.CreateUserStub = stub
}

func (fake *FakeRepo) CreateUserArgsForCall(i int) (context.Context, string, string) {
	fake.createUserMutex.RLock()
	defer fake.createUserMutex.RUnlock()
	argsForCall := fake.createUserArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeRepo) CreateUserReturns(result1 *models.User, result2 error) {
	fake.createUserMutex.Lock()
	defer fake.createUserMutex.Unlock()
	fake.CreateUserStub = nil
	fake.createUserReturns = struct {
		result1 *models.User
		result2 error
	}{result1, result2}
}

func (fake *FakeRepo) CreateUserReturnsOnCall(i int, result1 *models.User, result2 error) {
	fake.createUserMutex.Lock()
	defer fake.createUserMutex.Unlock()
	fake.CreateUserStub = nil
	if fake.createUserReturnsOnCall == nil {
		fake.createUserReturnsOnCall = make(map[int]struct {
			result1 *models.User
			result2 error
		})
	}
	fake.createUserReturnsOnCall[i] = struct {
		result1 *models.User
		result2 error
	}{result1, result2}
}

func (fake *FakeRepo) GetLeagues(arg1 context.Context) ([]*models.League, error) {
	fake.getLeaguesMutex.Lock()
	ret, specificReturn := fake.getLeaguesReturnsOnCall[len(fake.getLeaguesArgsForCall)]
	fake.getLeaguesArgsForCall = append(fake.getLeaguesArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GetLeaguesStub
	fakeReturns := fake.getLeaguesReturns
	fake.recordInvocation("GetLeagues", []interface{}{arg1})
	fake.getLeaguesMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRepo) GetLeaguesCallCount() int {
	fake.getLeaguesMutex.RLock()
	defer fake.getLeaguesMutex.RUnlock()
	return len(fake.getLeaguesArgsForCall)
}

func (fake *FakeRepo) GetLeaguesCalls(stub func(context.Context) ([]*models.League, error)) {
	fake.getLeaguesMutex.Lock()
	defer fake.getLeaguesMutex.Unlock()
	fake.GetLeaguesStub = stub
}

func (fake *FakeRepo) GetLeaguesArgsForCall(i int) context.Context {
	fake.getLeaguesMutex.RLock()
	defer fake.getLeaguesMutex.RUnlock()
	argsForCall := fake.getLeaguesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeRepo) GetLeaguesReturns(result1 []*models.League, result2 error) {
	fake.getLeaguesMutex.Lock()
	defer fake.getLeaguesMutex.Unlock()
	fake.GetLeaguesStub = nil
	fake.getLeaguesReturns = struct {
		result1 []*models.League
		result2 error
	}{result1, result2}
}

func (fake *FakeRepo) GetLeaguesReturnsOnCall(i int, result1 []*models.League, result2 error) {
	fake.getLeaguesMutex.Lock()
	defer fake.getLeaguesMutex.Unlock()
	fake.GetLeaguesStub = nil
	if fake.getLeaguesReturnsOnCall == nil {
		fake.getLeaguesReturnsOnCall = make(map[int]struct {
			result1 []*models.League
			result2 error
		})
	}
	fake.getLeaguesReturnsOnCall[i] = struct {
		result1 []*models.League
		result2 error
	}{result1, result2}
}

func (fake *FakeRepo) GetUserByUsername(arg1 context.Context, arg2 string) (*models.User, error) {
	fake.getUserByUsernameMutex.Lock()
	ret, specificReturn := fake.getUserByUsernameReturnsOnCall[len(fake.getUserByUsernameArgsForCall)]
	fake.getUserByUsernameArgsForCall = append(fake.getUserByUsernameArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetUserByUsernameStub
	fakeReturns := fake.getUserByUsernameReturns
	fake.recordInvocation("GetUserByUsername", []interface{}{arg1, arg2})
	fake.getUserByUsernameMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRepo) GetUserByUsernameCallCount() int {
	fake.getUserByUsernameMutex.RLock()
	defer fake.getUserByUsernameMutex.RUnlock()
	return len(fake.getUserByUsernameArgsForCall)
}

func (fake *FakeRepo) GetUserByUsernameCalls(stub func(context.Context, string) (*models.User, error)) {
	fake.getUserByUsernameMutex.Lock()
	defer fake.getUserByUsernameMutex.Unlock()
	fake.GetUserByUsernameStub = stub
}

func (fake *FakeRepo) GetUserByUsernameArgsForCall(i int) (context.Context, string) {
	fake.getUserByUsernameMutex.RLock()
	defer fake.getUserByUsernameMutex.RUnlock()
	argsForCall := fake.getUserByUsernameArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeRepo) GetUserByUsernameReturns(result1 *models.User, result2 error) {
	fake.getUserByUsernameMutex.Lock()
	defer fake.getUserByUsernameMutex.Unlock()
	fake.GetUserByUsernameStub = nil
	fake.getUserByUsernameReturns = struct {
		result1 *models.User
		result2 error
	}{result1, result2}
}

func (fake *FakeRepo) GetUserByUsernameReturnsOnCall(i int, result1 *models.User, result2 error) {
	fake.getUserByUsernameMutex.Lock()
	defer fake.getUserByUsernameMutex.Unlock()
	fake.GetUserByUsernameStub = nil
	if fake.getUserByUsernameReturnsOnCall == nil {
		fake.getUserByUsernameReturnsOnCall = make(map[int]struct {
			result1 *models.User
			result2 error
		})
	}
	fake.getUserByUsernameReturnsOnCall[i] = struct {
		result1 *models.User
		result2 error
	}{result1, result2}
}

func (fake *FakeRepo) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRepo) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ models.Repo = new(FakeRepo)
